angular.module('ngRepeat', ['ngAnimate']).controller('repeatController', function($scope) {
  $scope.companies = [
    /*{company:'name',address1:'address line one',address2:'address line two',email:'name@place.com',phone:'415-123-4567',image:'www.imageurl.com/imagename.jpg'},*/
{company:'Arbok Ekans',address1:'565 Clay St.',address2:'San Francisco, CA 94111',email:'johndoe@gmail.com',phone:'415-222-1234',image:'logo12.jpg',actual:'$10,000,000',pipeline:'$7,500,000',opp:80,notes:'Reviewed performance with SW regional head. Discussed promo plan to improve performance in Q3. Reviewed sales agreement with client and legal team. Awaiting final legal approval.',opp2:'success'},
{company:'Aspen Holdings',address1:'100 1st Street',address2:'San Francisco, CA 94105',email:'johndoe@gmail.com',phone:'415-222-1234',image:'logo9.jpg',actual:'$900,000',pipeline:'$90,000',opp:85,notes:'Reviewed performance with SW regional head. Discussed promo plan to improve performance in Q3. Reviewed sales agreement with client and legal team. Awaiting final legal approval.',opp2:'success'},
{company:'Dratini Darts',address1:'780 Market Street',address2:'San Francisco, CA 94103',email:'johndoe@gmail.com',phone:'415-222-1234',image:'logo3.jpg',actual:'$800,000',pipeline:'$725,000',opp:77,notes:'Reviewed performance with SW regional head. Discussed promo plan to improve performance in Q3. Reviewed sales agreement with client and legal team. Awaiting final legal approval.',opp2:'warning'},
{company:'Finch Media',address1:'7 3rd Street',address2:'San Francisco, CA 94103',email:'johndoe@gmail.com',phone:'415-222-1234',image:'logo10.jpg',actual:'$8,000,000',pipeline:'$1,600,000',opp:62,notes:'Reviewed performance with SW regional head. Discussed promo plan to improve performance in Q3. Reviewed sales agreement with client and legal team. Awaiting final legal approval.',opp2:'warning'},
{company:'Genesee & Wyoming',address1:'299 2nd Street',address2:'San Francisco, CA 94105',email:'johndoe@gmail.com',phone:'415-222-1234',image:'logo6.jpg',actual:'$180,000',pipeline:'$140,000',opp:48,notes:'Reviewed performance with SW regional head. Discussed promo plan to improve performance in Q3. Reviewed sales agreement with client and legal team. Awaiting final legal approval.',opp2:'danger'},
{company:'Global Learning',address1:'199 Fremont Street',address2:'San Francisco, CA 94105',email:'johndoe@gmail.com',phone:'415-222-1234',image:'logo4.jpg',actual:'$3,000,000',pipeline:'$3,000,000',opp:100,notes:'Reviewed performance with SW regional head. Discussed promo plan to improve performance in Q3. Reviewed sales agreement with client and legal team. Awaiting final legal approval.',opp2:'success'},
{company:'Goldeen Coast, Inc.',address1:'201 Spear Street',address2:'San Francisco, CA 94105',email:'johndoe@gmail.com',phone:'415-222-1234',image:'logo5.jpg',actual:'$125,000',pipeline:'$95,000',opp:68,notes:'Reviewed performance with SW regional head. Discussed promo plan to improve performance in Q3. Reviewed sales agreement with client and legal team. Awaiting final legal approval.',opp2:'warning'},
{company:'Nidoran Onix',address1:'123 Mission Street',address2:'San Francisco, CA 94105',email:'johndoe@gmail.com',phone:'415-222-1234',image:'logo8.jpg',actual:'$200,000',pipeline:'$220,000',opp:88,notes:'Reviewed performance with SW regional head. Discussed promo plan to improve performance in Q3. Reviewed sales agreement with client and legal team. Awaiting final legal approval.',opp2:'success'},
{company:'Paras',address1:'27 Drumm Street',address2:'San Francisco, CA 94111-4805',email:'johndoe@gmail.com',phone:'415-222-1234',image:'logo2.jpg',actual:'$2,000,000',pipeline:'$1,500,000',opp:92,notes:'Reviewed performance with SW regional head. Discussed promo plan to improve performance in Q3. Reviewed sales agreement with client and legal team. Awaiting final legal approval.',opp2:'success'},
{company:'Sandshrew Grilled Cheese & Co.',address1:'295 California Street',address2:'San Francisco, CA 94111',email:'johndoe@gmail.com',phone:'415-222-1234',image:'logo7.jpg',actual:'$500,000',pipeline:'$100,000',opp:75,notes:'Reviewed performance with SW regional head. Discussed promo plan to improve performance in Q3. Reviewed sales agreement with client and legal team. Awaiting final legal approval.',opp2:'warning'},
{company:'Spearow Industries',address1:'44 Montgomery Street',address2:'San Francisco, CA 94104',email:'johndoe@gmail.com',phone:'415-222-1234',image:'logo1.jpg',actual:'$1,000,000',pipeline:'$600,000',opp:93,notes:'Reviewed performance with SW regional head. Discussed promo plan to improve performance in Q3. Reviewed sales agreement with client and legal team. Awaiting final legal approval.',opp2:'success'},
{company:'Vulpix Film & Audio',address1:'359 Grant Street',address2:'San Francisco, CA 94108',email:'johndoe@gmail.com',phone:'415-222-1234',image:'logo11.jpg',actual:'$3,000,000',pipeline:'$6,000,000',opp:71,notes:'Reviewed performance with SW regional head. Discussed promo plan to improve performance in Q3. Reviewed sales agreement with client and legal team. Awaiting final legal approval.',opp2:'warning'},
{company:'Add New Account',address1:'',address2:'',email:'',phone:'',image:'logo13.jpg',actual:'',pipeline:'',opp:41,notes:'Add new account.',opp2:'warning'}
	];
/*});*/

/*angular.module('ngRepeat', ['ngAnimate']).controller('repeatController', function($scope) {*/
  $scope.notes = [
  /*{title:'Note Title',createdBy:'Creator Name',createdOn:'Created Date',type:'Note Type',star:'Color',note:'Note copy goes in here.'},*/
{title:'Gothams',createdBy:'John B. Day',createdOn:'April 1, 1883',type:'Follow Up',star:'danger',note:'The Giants began as the second baseball club founded by millionaire tobacconist John B. Day and veteran amateur baseball player Jim Mutrie. The Gothams, as the Giants were originally known, entered the National League in 1883.'},
{title:'Gothams 2',createdBy:'Jim Mutrie',createdOn:'April 20, 1883',type:'Follow Up',star:'success',note:'Nearly half of the original Gotham players were members of the disbanded Troy Trojans, whose place in the National League the Gothams inherited.'},
{title:'Bridegrooms',createdBy:'John McGraw',createdOn:'January 9, 2007',type:'Follow Up',star:'success',note:'While the Metropolitans were initially the more successful club, Day and Mutrie began moving star players to the Gothams, and in 1888 the team won its first National League pennant.'},
{title:'Bridegrooms',createdBy:'John McGraw',createdOn:'Septemer 22, 2007',type:'Follow Up',star:'danger',note:'They repeated as champions the next year with a pennant and Championship victory over the Brooklyn Bridegrooms.'},
{title:'Giants',createdBy:'John McGraw',createdOn:'August 9, 2007',type:'Follow Up',star:'warning',note:'It is said that after one particularly satisfying victory over the Philadelphia Phillies, Mutrie (who was also the team manager) stormed into the dressing room and exclaimed, "My big fellows! My giants!" From then on, the club was known as the Giants.'},
{title:'Giants',createdBy:'John McGraw',createdOn:'September 26, 2007',type:'Follow Up',star:'success',note:'The Giants original home stadium, the Polo Grounds, dates from this early era. It was originally located north of Central Park adjacent to 5th and 6th Avenues and 110th and 112th Streets, in Harlem in upper Manhattan.'},
{title:'Giants',createdBy:'Rogers Hornsby',createdOn:'April 29, 2008',type:'Follow Up',star:'danger',note:'The Giants were a powerhouse in the late 1880s, winning their first two National League Pennants and World Championships in 1888 and 1889.'},
{title:'Giants',createdBy:'Mel Ott',createdOn:'June 15, 2015',type:'Follow Up',star:'danger',note:'But nearly all of the Giants stars jumped to the upstart Players League, whose New York franchise was also named the Giants, in 1890. The new team even built a stadium next door to the Polo Grounds.'},
{title:'Giants',createdBy:'Bill Terry',createdOn:'June 15, 2015',type:'Follow Up',star:'success',note:'With a decimated roster, the National League Giants finished a distant sixth. Attendance took a nosedive, and the financial strain affected Days tobacco business as well. The Players League dissolved after the season, and Day sold a minority interest in his NL Giants to the defunct PL Giants principal backer, Edward Talcott.'},
{title:'Gigantes',createdBy:'Casey Stengel',createdOn:'June 15, 2015',type:'Follow Up',star:'primary',note:'As a condition of the sale, Day had to fire Mutrie as manager. Although the Giants rebounded to third in 1891, Day was forced to sell a controlling interest to Talcott at the end of the season.'},
{title:'Gigantes',createdBy:'Jim Thorpe',createdOn:'June 15, 2015',type:'Follow Up',star:'success',note:'Four years later, Talcott sold the Giants to Andrew Freedman, a real estate developer with ties to the Tammany Hall political machine running New York City. Freedman was one of the most detested owners in baseball history, getting into heated disputes with other owners, and with star pitcher Amos Rusie, author of the first Giants no-hitter.'},
{title:'Giants',createdBy:'Ban Johnson',createdOn:'June 15, 2015',type:'Follow Up',star:'success',note:'hen Freedman offered Rusie only $2,500 to play in 1896, the disgruntled hurler sat out the entire season. Attendance fell off throughout the league without Rusie, prompting the other owners to chip in $50,000 to get him to return for 1897.'}
	];
	
$scope.showPopup = function(theLogo, theCompany, addy1, addy2, email, phone) {
	//alert(theLogo + " " + theCompany);
	document.getElementById("mfsPopupContact").className = "mfsPopup";
	document.getElementById("mfsPopupBubbleLOGO").setAttribute("src", "/mfs/img/"+theLogo+"");
	document.getElementById("mfsPopupBubbleTTL").innerHTML = theCompany;
	document.getElementById("mfsAddy1").innerHTML = addy1;
	document.getElementById("mfsAddy2").innerHTML = addy2;
	document.getElementById("mfsEmail1").innerHTML = email;
	document.getElementById("mfsPhone1").innerHTML = phone;
}
});